name: Run Discord Bot

on:
  schedule:
    - cron: "5 0 * * *" # 매일 UTC 00:05 (한국 시간 오전 9:05)에 실행
  workflow_dispatch: # 수동 실행 옵션

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py openai
      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          AUTHORIZED_USERS: ${{ secrets.AUTHORIZED_USERS }}
        run: python bot.py
