name: Run Discord Bot

on:
  schedule:
    - cron: "5 0 * * *" # 매일 UTC 00:05 (한국 시간 오전 9:05)에 실행
  workflow_dispatch: # 수동 실행 옵션

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          READ_CHANNEL_ID: ${{ secrets.READ_CHANNEL_ID }}
          SEND_CHANNEL_ID: ${{ secrets.SEND_CHANNEL_ID }}
          AUTHORIZED_USERS: ${{ secrets.AUTHORIZED_USERS }}
        run: python bot.py
